# Generated by Django 3.2 on 2021-05-05 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specie',
            name='characters',
        ),
        migrations.AddField(
            model_name='personaggio',
            name='specie',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='character_manager.specie'),
            preserve_default=False,
        ),
    ]
