# Generated by Django 3.2 on 2021-05-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_manager', '0002_auto_20210505_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaggio',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
