# Generated by Django 3.2 on 2021-05-31 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character_manager', '0004_auto_20210529_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='incantesimo',
            name='descrizione',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='safare',
            name='grado',
            field=models.IntegerField(choices=[(1, 'Mezza proficiency'), (2, 'Proficiency'), (3, 'Expertise')], default=2),
        ),
    ]
