# Generated by Django 3.2 on 2021-05-05 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('character_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campagna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=64)),
                ('descrizione', models.TextField()),
                ('personaggi', models.ManyToManyField(to='character_manager.Personaggio')),
            ],
        ),
        migrations.CreateModel(
            name='Gruppo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
                ('attivo', models.BooleanField(default=False)),
                ('campagna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bard.campagna')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Partecipa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comeDm', models.BooleanField(default=False)),
                ('campagna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bard.campagna')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Messaggio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.PositiveSmallIntegerField(choices=[(1, 'Testo'), (2, 'Messaggi')], default=1)),
                ('contenuto', models.TextField()),
                ('ora', models.DateTimeField()),
                ('gruppo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bard.gruppo')),
                ('in_risposta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bard.messaggio')),
            ],
        ),
        migrations.AddField(
            model_name='campagna',
            name='utenti',
            field=models.ManyToManyField(through='bard.Partecipa', to=settings.AUTH_USER_MODEL),
        ),
    ]
