# Generated by Django 3.2 on 2021-06-07 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('character_manager', '0005_auto_20210531_1129'),
        ('bard', '0002_messaggio_utente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campagna',
            name='personaggi',
            field=models.ManyToManyField(related_name='personaggi_campagna', to='character_manager.Personaggio'),
        ),
        migrations.AlterField(
            model_name='campagna',
            name='utenti',
            field=models.ManyToManyField(related_name='partecipanti_campagna', through='bard.Partecipa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gruppo',
            name='campagna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campagna_gruppo', to='bard.campagna'),
        ),
        migrations.AlterField(
            model_name='gruppo',
            name='users',
            field=models.ManyToManyField(related_name='utenti_gruppo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messaggio',
            name='gruppo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gruppo_messaggio', to='bard.gruppo'),
        ),
        migrations.AlterField(
            model_name='messaggio',
            name='in_risposta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risposta', to='bard.messaggio'),
        ),
        migrations.AlterField(
            model_name='messaggio',
            name='utente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utente_messaggio', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='partecipa',
            name='campagna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campagna_partecipa', to='bard.campagna'),
        ),
        migrations.AlterField(
            model_name='partecipa',
            name='utente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utente_partecipa', to=settings.AUTH_USER_MODEL),
        ),
    ]
